import Nav from '@/components/nav'
import Provider from '@/components/provider'
import '@/styles/main.scss'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Nuxt GPT App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <div className="main"> 
           <div className=""> 
             <main className="app"> 
              <Provider>
                <Nav />
                {children}
              </Provider>
             </main> 
           </div> 
         </div> 
      </body> 
    </html>
  )
}
